[package]
name = "xoodoo"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>", "Frank Denis <github@pureftpd.org>"]
edition = "2018"
description = "Xoodyak / Xoodoo - A versatile cryptographic scheme that can be used for hashing, encryption, MAC computation and authenticated encryption."
readme = "README.md"
keywords = ["crypto", "xoodyak", "xoodoo", "cyclist"]
license = "MIT"
homepage = "https://github.com/ipfs-rust/xoodoo"
repository = "https://github.com/ipfs-rust/xoodoo"
categories = ["no-std", "cryptography", "wasm"]

[features]
default = ["std"]
std = []

[dependencies]
core_simd = { path = "../stdsimd/crates/core_simd" }
rawbytes = "0.1"
zeroize = "1.2"

[dev-dependencies]
criterion = "0.3"

[profile.release]
codegen-units = 1
incremental = false
panic = "abort"
lto = "fat"

[profile.bench]
codegen-units = 1

[[bench]]
name = "benchmark"
harness = false
